openapi: 3.2.0
info:
  version: 1.1.0
  title: Peakon Answers API
  description: The Public Peakon API
servers:
- url: https://{subdomain}.peakon.com/api/v1/
  variables:
    subdomain:
      description: Unique subdomain assigned to your Peakon instance.
      default: api
tags:
- name: Answers
paths:
  /answers/export:
    get:
      tags:
      - Answers
      summary: Get survey answers
      parameters:
      - name: per_page
        required: true
        description: The maximum number of survey answers returned per page
        schema:
          type: integer
          minimum: 1
          maximum: 20000
        in: query
      security:
      - jwt: []
      responses:
        '200':
          description: A list of survey answer with related fields included
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: A unique numeric ID identifying the answer
                        type:
                          type: string
                          description: Is always 'answers_export'
                          enum:
                          - answers_export
                        attributes:
                          type: object
                          properties:
                            accountEmail:
                              type:
                              - string
                              - 'null'
                              description: Email of the participating employee
                            answerId:
                              type: integer
                              description: An ID that uniquely identifies the answer
                            answerComment:
                              type:
                              - string
                              - 'null'
                              description: A comment given by the participating employee for the given question
                            answerLocale:
                              type:
                              - string
                              - 'null'
                              description: A locale that was detected based on the answers given during the survey. If possible the language of questionText will match this.
                            answerScore:
                              type:
                              - integer
                              - 'null'
                              description: The score given by participating employee for the given question
                            answerSkipReason:
                              type:
                              - string
                              - 'null'
                              description: If the question was skipped, this field contain the reason
                            answerText:
                              type:
                              - string
                              - 'null'
                              description: If the question should be answered with text and not a score, this field contain the answer given
                            categoryGroup:
                              type:
                              - string
                              - 'null'
                              description: The set of questions that the asked question belong to
                            categoryId:
                              type:
                              - string
                              - 'null'
                              description: An ID that uniquely identifies the category/driver that the asked question belong to
                            categoryStandard:
                              type:
                              - string
                              - 'null'
                              description: Can be used to identify built-in categories/drivers across companies
                            companyId:
                              type:
                              - integer
                              - 'null'
                              description: An ID that uniquely identifies the company
                            employeeExternalId:
                              type:
                              - string
                              - 'null'
                              description: A company-specified ID that can used to identify an employee
                            employeeId:
                              type:
                              - string
                              - 'null'
                              description: An ID that uniquely identifies the employee
                            questionId:
                              type:
                              - string
                              - 'null'
                              description: An ID that uniquely identifies the asked question. Each question has translations so that questionText in different locales ties into the same questionId.
                            questionText:
                              type:
                              - string
                              - 'null'
                              description: The text of the question being asked. The language of questionText will match answerLocale. Default is the question text seen in the Peakon product.
                            questionType:
                              type:
                              - string
                              - 'null'
                              description: The type of question asked.
                              enum:
                              - scale
                              - text
                              - value
                            responseAnsweredAt:
                              type:
                              - string
                              - 'null'
                              format: date-time
                              description: The time when the survey response was submitted
                            responseId:
                              type:
                              - integer
                              - 'null'
                              description: An ID that uniquely identifies the asked response
                            roundEnd:
                              type:
                              - string
                              - 'null'
                              format: date
                              description: A date for when the survey round ended
                            roundId:
                              type:
                              - integer
                              - 'null'
                              description: An ID that uniquely identifies the round
                            roundOpensAt:
                              type:
                              - string
                              - 'null'
                              format: date
                              description: A date for when the survey round opened
                            roundType:
                              type:
                              - string
                              - 'null'
                              description: Is "test" if the survey is a test survey. "automatic" otherwise.
                              enum:
                              - automatic
                              - test
                            scheduleContextName:
                              type:
                              - string
                              - 'null'
                              description: The name of the Company or Segment that the schedule is for
                            scheduleId:
                              type:
                              - integer
                              - 'null'
                              description: An ID that uniquely identifies the schedule
                  links:
                    type: object
                    properties:
                      first:
                        type: string
                        format: uri
                      self:
                        type: string
                        format: uri
                      next:
                        type:
                        - string
                        - 'null'
                        format: uri
      operationId: getAnswersExport
      x-operation-id-source: derived
